// Autogenerated by Thrift Compiler (facebook)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// @generated

package storage

import (
	"bytes"
	"context"
	"fmt"
	thrift "github.com/facebook/fbthrift/thrift/lib/go/thrift"
	meta1 "github.com/harrischu/nebula-wrapper/pkg/thrift/3.0/nebula/meta"
	nebula0 "github.com/harrischu/nebula-wrapper/pkg/thrift/3.0/nebula"
	"sync"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = sync.Mutex{}
var _ = bytes.Equal
var _ = context.Background

var _ = nebula0.GoUnusedProtection__
var _ = meta1.GoUnusedProtection__

func init() {
}
